main: net.nafana.TrainsCore.TrainsCore
name: TrainsCore
version: '1.0-SNAPSHOT'
description: The core for all train mechanics on the server
load: POSTWORLD
author: Nafana
website: spigotmc.org
depend: [WorldEdit]

# Comments!

commands:
  spawntrain:
    description: Spawns in a train at your location.
    usage: /spawntrain <TRAIN_NAME>
  addtrain:
    description: Adds a train to the configuration.
    usage: /addtrain <TRAIN_NAME>
  guidebug:
    description: Debug GUI menu
    usage: /guidebug
  menu:
    description: Opens the player menu
    usage: /menu